name: Cross-compatibility

# This workflow runs the unit tests across a range of Python versions and operating
# systems.

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Orca
      run: |
        pip install .
        pip install flask pygments  # for server component tests
    - name: Run unit tests
      run: |
        pip install pytest
        pytest -s
