name: Unit tests

# This workflow runs the unit tests in a single generic environment (recent but stable
# Python version on recent but stable Ubuntu). The cross-compatibility.yml workflow runs
# the same tests across multiple platforms.

on:
  push:
  # pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Orca
      run: |
        pip install .
        pip install flask pygments  # for server component tests
    - name: Run unit tests
      run: |
        pip install pytest
        pytest -s
